baseURL: https://blog.shaishav.kr
languageCode: en-us
title: Shaishav Kumar
paginate: 10
theme: "PaperMod"

markup:
  # defaultMarkdownHandler: pandoc
  # pandoc:
    # renderer:
      # unsafe : true
  goldmark:
    renderer:
      unsafe : true

security:
  enableInlineShortcodes: false
  exec:
    allow: ["^dart-sass-embedded$", "^go$", "^npx$", "^postcss$", "^pandoc"]
    osEnv: ["(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$"]

assetDir: ./assets


module:
  mounts:
    - source: 'static'
      target : 'static'
    - source : 'assets'
      target : 'static/Assets'


enableRobotsTXT: true

buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true


params:
  env: production # to enable go

  author: "Shaishav Kumar"
  contact: "kr.shaishav@gmail.com"
  feedlinks: true
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  mobileMenu: true
  
  DateFormat: "January 2, 2006"
  defaultTheme: dark #auto, light
  disableThemeToggle: true



  

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  UseHugoToc: true
  showtoc: true
  tocopen: true

  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page
  
  fuseOpts: 
    isCaseSensitive: false
    shouldSort: true
    minMatchCharLength: 3
    
  
  
  label:
    text: "<mark>@wiresurfer</mark> | Shaishav Kumar"
    # icon: /img/shaishav-logo-bw.png
  
  homeInfoParams:
    Title: |
      ![Shaishav Kumar profile pic](./img/profile-pic.png "Shaishav.kr")

    Cta: |
    
    Content: |
        <sup>Voila, you've stumbled upon this nook of the interwebs</sup>
        <sup>let me introduce myself and thank you for dropping by ğŸ‘‹</sup>
        <br />
        <br />
        
        ### My Journey 
        
        ```
        With 15+ years or expereince working in Machine Learning, Cloud and Distributed Systems Engineering, 
        and Enterprise Fullstack Web and Mobile development, I have a treasure trove of knowledge, 
        expereince and real word case studies worth sharing. 
        
        More recently, I have spent 9+ years successfully running small, high-paced, high-performance
        engineering teams in 0-to-1 & 1-scale startups. 
        ```
        <br />
        
        ### My Mission
        ```
        1. Solving "hard" engineering problems, not confined to software running inside the "box"
        2. At the intersection of Computer Science and the Physical World via "Smart Hardware"
        3. In domains which can have a measurable impact in the "betterment" of "human condition"
        ```
        <br />
        
        ### My Writing usually talks about
        ```
        1. ğŸ‘·â€â™‚ï¸ Engineering
            1. ğŸŒ IoT,  ğŸ¤– Robotics, ğŸ–¥ï¸ğŸ§  Machine Learning and AI 
            3. Golang, â˜¸ Kubernetes, ğŸ³Docker & friends.   
        2. ğŸ’¼ Management and Strategy
            1. ğŸ™‡ Learnings on Engineering leadership for small yet high-impact teams
            2. ğŸŒ Practices for managing high-output remote-first global teams.
            3. ğŸš€ Startups & Strategy & Tips on Building Great Technical B2B Products
        3. ğŸ§  Right brain musings (in small, infrequent doses)
            1. âŒšProductivty , ğŸ“¸ Photography, ğŸ“– Philosophy, and ğŸ¥³ Happiness 
        ```  

        <br />
        <br />


  socialIcons: # optional
    - name: "github"
      url: "https://github.com/wiresurfer"
    # - name: "youtube"
    #   url: "https://www.youtube.com/channel/XXX"
    - name: "twitter"
      url: "https://twitter.com/wiresurfer"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/shaishavkr/"
      
    # - name: "kofi"
    #   url: "https://buymeacoffee.com/XXX"
    # - name: "rss"
    #   url: "https://XXX.github.io/index.xml"
  
  
  custom_css:
    - "css/custom.css"
    - "css/obsidian.css"
    - 
  custom_js:
    - "js/jquery.js"
    - "js/mermaid.js"
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
  section:
    - HTML
    - RSS
    - JSON

taxonomies:
  tag: tags
  category: categories
  
menu:
  main:
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 20
    # - identifier: archive
      # name: Archive
      # url: /archives/
      # weight: 20

frontmatter:
  date: 
    - publishDate
    - :filename
    - date
    - :fileModTime
  publishDate: 
    - publishDate
    - :filename
    - date
    - :fileModTime